export const mockCardData = {
  object: "card",
  id: "test-id",
  oracle_id: "test-oracle-id",
  multiverse_ids: [123456],
  name: "Lightning Bolt",
  lang: "en",
  released_at: "2023-01-01",
  uri: "https://api.scryfall.com/cards/test-id",
  scryfall_uri: "https://scryfall.com/card/test/123/lightning-bolt",
  layout: "normal",
  highres_image: true,
  image_status: "highres_scan",
  image_uris: {
    small: "https://cards.scryfall.io/small/test.jpg",
    normal: "https://cards.scryfall.io/normal/test.jpg",
    large: "https://cards.scryfall.io/large/test.jpg",
    png: "https://cards.scryfall.io/png/test.png",
    art_crop: "https://cards.scryfall.io/art_crop/test.jpg",
    border_crop: "https://cards.scryfall.io/border_crop/test.jpg",
  },
  mana_cost: "{R}",
  cmc: 1,
  type_line: "Instant",
  oracle_text: "Lightning Bolt deals 3 damage to any target.",
  colors: ["R"],
  color_identity: ["R"],
  keywords: [],
  legalities: {
    standard: "not_legal",
    modern: "legal",
  },
  games: ["paper"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: false,
  promo: false,
  reprint: false,
  variation: false,
  set_id: "test-set-id",
  set: "test",
  set_name: "Test Set",
  set_type: "core",
  set_uri: "https://api.scryfall.com/sets/test",
  set_search_uri: "https://api.scryfall.com/cards/search?q=e%3Atest",
  scryfall_set_uri: "https://scryfall.com/sets/test",
  rulings_uri: "https://api.scryfall.com/cards/test-id/rulings",
  prints_search_uri:
    "https://api.scryfall.com/cards/search?q=%21%22Lightning+Bolt%22",
  collector_number: "123",
  digital: false,
  rarity: "common",
  card_back_id: "test-back-id",
  artist: "Test Artist",
  border_color: "black",
  frame: "2015",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  prices: {
    usd: "0.10",
  },
  related_uris: {},
};
